---
- name: Ensure filesystem is mounted
  become: true
  ansible.posix.mount:
    path: "{{ outer_item.path }}"
    src: "{{ outer_item.src }}"
    fstype: "{{ outer_item.fstype }}"
    opts: "{{ outer_item.opts }}"
    dump: "{{ outer_item.dump | default(omit) }}"
    passno: "{{ outer_item.passno | default(omit) }}"
    state: mounted
