---
- name: Set time backend
  ansible.builtin.assert:
    that:
      - time_backend in ['chrony', 'systemd-timesyncd']
    fail_msg: "Invalid time backend: {{ time_backend }}"

- name: Ensure tzdata package is installed
  ansible.builtin.package:
    name: "{{ time_tzdata_package }}"
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ time_timezone }}"

- name: Remove other time synchronization packages if present
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ time_ntp_legacy_packages }}"

- name: Ensure chrony is configured
  ansible.builtin.include_tasks: chrony.yml

- name: Ensure systemd-timesyncd is configured
  ansible.builtin.include_tasks: systemd-timesync.yml
