---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Ensure systemd-timesyncd service is stopped
  when: time_backend != 'systemd-timesyncd'
  ansible.builtin.systemd:
    name: "{{ time_timesyncd_service }}"
    enabled: false
    state: stopped
    ignore_errors: true

- name: Ensure systemd-timesyncd package is present
  ansible.builtin.package:
    name: "{{ time_timesyncd_package }}"
    state: "{{ 'present' if time_backend == 'systemd-timesyncd' else 'absent' }}"

- name: Manage systemd-timesyncd configuration
  become: true
  when: time_backend == 'systemd-timesyncd'
  block:
    - name: Ensure systemd-timesyncd service is enabled and running
      ansible.builtin.systemd:
        name: "{{ time_timesyncd_service }}"
        enabled: true
        state: started

    - name: Configure time synchronization settings
      ansible.builtin.lineinfile:
        dest: /etc/systemd/timesyncd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: '\[Time\]'
        backrefs: true
        state: present
        mode: '0644'
      loop:
        - regexp: '^\s*#?\s*(NTP=).*$'
          line: 'NTP={{ time_ntp_servers | join(" ") }}'
        - regexp: '^\s*#?\s*(ConnectionRetrySec=).*$'
          line: 'ConnectionRetrySec={{ time_timesyncd_connection_retry }}'
        - regexp: '^\s*#?\s*(RootDistanceMaxSec=).*$'
          line: 'RootDistanceMaxSec={{ time_timesyncd_root_distance_max }}'
        - regexp: '^\s*#?\s*(PollIntervalMinSec=).*$'
          line: 'PollIntervalMinSec={{ time_timesyncd_poll_interval_min }}'
        - regexp: '^\s*#?\s*(PollIntervalMaxSec=).*$'
          line: 'PollIntervalMaxSec={{ time_timesyncd_poll_interval_max }}'
      notify:
        - Restart timesyncd
