galaxy_info:
  author: Julien K.
  description: protect services with fail2ban

  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - security
    - fail2ban
    - ssh

dependencies: []
