galaxy_info:
  author: Julien K.
  description: manage host hostname and optional /etc/hosts entry

  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - hostname
    - networking
    - system

dependencies: []
