galaxy_info:
  author: Julien K.
  description: manage /etc/motd content

  license: MIT

  min_ansible_version: 2.20

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - motd
    - system

dependencies: []
