galaxy_info:
  author: Julien K.
  description: manage PAM password quality settings

  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - pam
    - security

dependencies: []
