galaxy_info:
  author: Julien K.
  description: manage nftables firewall rules

  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - security
    - firewall
    - nftables

dependencies: []
