---
nss_enabled: true
nsswitch_file: /etc/nsswitch.conf

nss_passwd: 'files systemd'
nss_group: 'files systemd'
nss_shadow: 'files'
nss_hosts: 'files dns'
nss_networks: 'files'
nss_protocols: 'files'
nss_services: 'files'
nss_netgroup: 'files'
