---
- name: Manage NSS configuration
  when:
    - ansible_facts['os_family'] == 'Debian'
    - nss_enabled | bool
  block:
    - name: Ensure nsswitch.conf is present
      become: true
      ansible.builtin.template:
        src: nsswitch.conf.j2
        dest: "{{ nsswitch_file }}"
        owner: root
        group: root
        mode: '0644'
