---
- name: Check supported OS family
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] | lower == 'debian'
    fail_msg: "nodejs role currently supports only Debian family hosts."

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: debian.yml
