---
- name: Configure static backend
  when: network_backend == 'static'
  block:
    - name: Ensure NetworkManager package is absent
      become: true
      ansible.builtin.apt:
        name: "{{ network_networkmanager_package }}"
        state: absent

    - name: Ensure NetworkManager service is disabled
      become: true
      ansible.builtin.systemd:
        name: "{{ network_networkmanager_service }}"
        enabled: false
        state: stopped
      when:
        - network_manage_services
        - network_nm_service_exists

    - name: Ensure systemd-networkd service is disabled
      become: true
      ansible.builtin.systemd:
        name: "{{ network_systemd_networkd_service }}"
        enabled: false
        state: stopped
      when:
        - network_manage_services
        - network_networkd_service_exists

    - name: Ensure systemd-networkd-wait-online service is disabled
      become: true
      ansible.builtin.systemd:
        name: "{{ network_systemd_networkd_wait_online_service }}"
        enabled: false
        state: stopped
      when:
        - network_manage_services
        - network_networkd_wait_online_service_exists
