---
- name: Manage node_exporter
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Ensure node_exporter package state matches node_exporter_enabled
      become: true
      ansible.builtin.apt:
        name: "{{ node_exporter_package }}"
        state: "{{ 'present' if node_exporter_enabled else 'absent' }}"

    - name: Configure and run node_exporter
      when: node_exporter_enabled | bool
      block:
        - name: Ensure node_exporter defaults file is present
          become: true
          ansible.builtin.template:
            src: prometheus-node-exporter.j2
            dest: "{{ node_exporter_defaults_file }}"
            owner: root
            group: root
            mode: '0644'
          notify: Restart node_exporter

        - name: Ensure node_exporter service is enabled and running
          become: true
          ansible.builtin.service:
            name: "{{ node_exporter_service }}"
            enabled: true
            state: started
