---
- name: Ensure node_exporter service state
  become: true
  ansible.builtin.systemd:
    name: "{{ node_exporter_service }}"
    enabled: "{{ node_exporter_enabled | bool }}"
    state: "{{ 'started' if node_exporter_enabled | bool else 'stopped' }}"

- name: Ensure node_exporter defaults file state
  become: true
  ansible.builtin.template:
    src: prometheus-node-exporter.j2
    dest: "{{ node_exporter_defaults_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart node_exporter
  when: node_exporter_enabled | bool

- name: Ensure node_exporter defaults file is absent
  become: true
  ansible.builtin.file:
    path: "{{ node_exporter_defaults_file }}"
    state: absent
  when: not node_exporter_enabled | bool

- name: Ensure node_exporter package state
  become: true
  ansible.builtin.package:
    pkg: "{{ node_exporter_package }}"
    state: "{{ 'present' if node_exporter_enabled | bool else 'absent' }}"
