---
- name: Restart chrony
  become: true
  ansible.builtin.systemd:
    name: "{{ time_chrony_service }}"
    state: restarted
  when: time_chrony_enabled | bool

- name: Restart timesyncd
  become: true
  ansible.builtin.systemd:
    name: "{{ time_timesyncd_service }}"
    state: restarted
  when: not time_chrony_enabled | bool
