---
- name: Configure sudo timestamp timeout
  become: true
  ansible.builtin.copy:
    dest: "{{ sudo_timeout_rule_path }}"
    owner: root
    group: root
    mode: '0440'
    validate: "{{ sudo_visudo_path }} -cf %s"
    content: "Defaults timestamp_timeout={{ sudo_timestamp_timeout }}\n"
  when: sudo_timestamp_timeout is not none

- name: Manage sudoers rules
  ansible.builtin.include_tasks: rule.yml
  loop: "{{ sudo_rules }}"
  loop_control:
    loop_var: sudo_rule
    label: "{{ sudo_rule.name }}"

- name: Remove unmanaged sudoers files
  when: sudo_rules_cleanup | bool
  block:
    - name: Find existing managed sudoers files
      become: true
      ansible.builtin.find:
        paths: "{{ sudo_rules_dir }}"
        patterns: "ansible_*"
      register: sudo_existing_files

    - name: Remove unmanaged sudoers files
      become: true
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ sudo_existing_files.files }}"
      when:
        - item.path not in sudo_rules | map(attribute='name') | map('regex_replace', '^(.*)$', sudo_rules_dir ~ '/ansible_\1') | list
