---
- name: "Apply sudoers rule: {{ sudo_rule.name }}"
  become: true
  ansible.builtin.template:
    src: sudoers_rule.j2
    dest: "{{ sudo_rules_dir }}/ansible_{{ sudo_rule.name }}"
    owner: root
    group: root
    mode: '0440'
    validate: "{{ sudo_visudo_path }} -cf %s"
  when: not (sudo_rule.absent | default(false))

- name: "Remove sudoers rule: {{ sudo_rule.name }}"
  become: true
  ansible.builtin.file:
    path: "{{ sudo_rules_dir }}/ansible_{{ sudo_rule.name }}"
    state: absent
  when: sudo_rule.absent | default(false)
